name: Clone
on: workflow_dispatch
jobs:
  deploy:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: |
          cd /pub/achen134/
          rm -rf Personal-Website
          git clone https://github.com/achen6159/Personal-Website.git
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD}}
