name: clone workflow
on: 
  workflow_dispatch:
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v2
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:achen6159/Personal-Website.git
