name: delete workflow
on: workflow_dispatch
jobs:
  deploy:
    name: Delete
    runs-on: ubuntu-latest
    steps:
    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: |
          unalias rm
          rm -rf Personal-Website
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD}}
